### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by cmacrae** [marc-sensenich/cert-manager-webhook-dnsimple#1]
Hey Marc 👋   

I hope you don't mind me opening this issue.  
I wanted to ask if you were planning on carrying on your work on this project? I've had a poke around the initial branch and it looks like you were off to a good start 🙂  

I was sad to see that cert-manager seemed to have dropped dnsimple as a core provider, after your earlier contribution in v0.3.  
I'm looking to issue certificates for my domain, which is hosted on dnsimple, so I'm very interested in your work here.

Please let me know if I can be of any help at all! I'm going to look over the code and see if I can get my head around it and if I can contribute at all.

**Comment by cmacrae** [comment]
Okay, I ended up bastardizing the code a bit over here:  
https://github.com/cmacrae/cert-manager-webhook-dnsimple/blob/master/main.go

This isn't me forking your work, I'd like to contribute to what you've already built - I just wanted to see if I could get my head around how this all worked. I'm well aware the quality of the code above isn't great (stripping out the methods and passing around a `dnsimple.Client` to functions, for instance), and it's untested - but am I sort of grapsing how this should end up piecing together?  

I tried implementing the `jetstack/cert-manager/pkg/acme/webhook.Solver` interface.  

Also, as outlined in their example, I decided to try out getting the access token from a Secret key reference.  

Anyway, perhaps this can serve as a basis for getting things rolling on the project. Looking forward to chatting when you have a moment 😊

**Comment by cmacrae** [comment]
I'll clean up the code and get it to a nice state, now that my initial learnings are out of the way :blush:   
I'm going to lean on https://github.com/cgroschupp/cert-manager-webhook-softlayer/blob/master/main.go as an implementation example, as it's the best I've seen so far.

**Comment by marc-sensenich** [comment]
@cmacrae my apologies for not responding to this issue at the time, I never saw these notifications. My organization went a different direction at the time and I never archived or continued work on this repo. I'm happy to see that https://github.com/neoskop/cert-manager-webhook-dnsimple has filled the void here and that you were able to find it!
